# Generated by Django 5.0.6 on 2024-05-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Image", models.ImageField(null=True, upload_to="images/")),
                ("EmailId", models.CharField(max_length=50)),
                ("PhoneNumber", models.CharField(max_length=50)),
                (
                    "PabblyApiToken",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Place", models.CharField(max_length=100, null=True)),
                ("City", models.CharField(max_length=100, null=True)),
                ("State", models.CharField(max_length=100, null=True)),
                ("Country", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("BarrierToken", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Callreasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CallReasons", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Callstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CallStatus", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Meetingoutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MeetingOutcome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LeadPurpose", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LeadSource", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LeadStatus", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taskcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TaskCategory", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompanyName", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=100)),
                ("Country", models.CharField(max_length=100)),
                ("PhoneNumber", models.CharField(max_length=12)),
                ("EmailId", models.EmailField(blank=True, max_length=200)),
                ("Website", models.CharField(blank=True, max_length=200)),
                (
                    "Admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.adminregister",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adminregister",
            name="Lid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CRM_App.login"
            ),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("FOR SALE", "For Sale"), ("OFF PLAN", "Off Plan")],
                        default="FOR SALE",
                        max_length=20,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[("RENTAL", "Rental"), ("SALE", "Sale")],
                        default="SALE",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=20)),
                ("bedrooms", models.CharField(max_length=20)),
                ("bathrooms", models.CharField(max_length=20)),
                ("area", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brochure",
                    models.FileField(
                        blank=True, null=True, upload_to="media/property_brochures/"
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.developer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.location",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.propertycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/property_images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="CRM_App.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Image", models.ImageField(null=True, upload_to="images/")),
                ("EmailId", models.CharField(max_length=50)),
                ("PhoneNumber", models.CharField(max_length=50)),
                ("Role", models.CharField(max_length=100)),
                ("Place", models.CharField(max_length=100, null=True)),
                ("City", models.CharField(max_length=100, null=True)),
                ("State", models.CharField(max_length=100, null=True)),
                ("Country", models.CharField(max_length=100, null=True)),
                (
                    "Admin",
                    models.CharField(
                        choices=[("YES", "yes"), ("NO", "no")],
                        default="NO",
                        max_length=20,
                    ),
                ),
                (
                    "Lid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.login"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.adminregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CustomerName", models.CharField(max_length=100)),
                ("CompanyName", models.CharField(max_length=100, null=True)),
                ("EmailId", models.CharField(max_length=50)),
                ("PhoneNumber", models.CharField(max_length=50)),
                ("AlternativeNumber", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=400)),
                ("Type", models.CharField(max_length=100)),
                ("Note", models.TextField(null=True)),
                ("Followup_title", models.CharField(max_length=100)),
                ("Followup_date", models.DateField()),
                ("Followup_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.adminregister",
                    ),
                ),
                (
                    "Purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.purpose",
                    ),
                ),
                (
                    "Source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.source"
                    ),
                ),
                (
                    "Staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.staff"
                    ),
                ),
                (
                    "Status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TaskName", models.CharField(max_length=100)),
                ("Comment", models.TextField(null=True)),
                ("Date", models.DateField()),
                ("Time", models.TimeField()),
                ("Description", models.TextField(null=True)),
                ("Status", models.CharField(max_length=50, null=True)),
                (
                    "AssignedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.adminregister",
                    ),
                ),
                (
                    "AssignedTo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.staff"
                    ),
                ),
                (
                    "CallReason",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.callreasons",
                    ),
                ),
                (
                    "CallStatus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.callstatus",
                    ),
                ),
                (
                    "Lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM_App.lead"
                    ),
                ),
                (
                    "MeetingOutcome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.meetingoutcome",
                    ),
                ),
                (
                    "TaskCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM_App.taskcategory",
                    ),
                ),
            ],
        ),
    ]
